apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zookeeperclusters.zookeeper.apache.org
spec:
  group: zookeeper.apache.org
  names:
    kind: ZookeeperCluster
    listKind: ZookeeperClusterList
    plural: zookeeperclusters
    singular: zookeepercluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: ZookeeperCluster is the Schema for the zookeeperclusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ZookeeperClusterSpec defines the desired state of ZookeeperCluster
            properties:
              environment: 
                type: string
              zookeeper:
                properties:
                  size: 
                    type: integer
                  updateStrategy:
                    properties:
                      type: 
                        type: string
                      rollingUpdate:
                        properties:
                          partition:
                            type: integer
                        type: object
                    type: object
                  image:
                    properties:
                      repository: 
                        type: string
                      tag: 
                        type: string
                      originTag: 
                        type: string
                      pullPolicy: 
                        type: string
                    type: object
                  pod:
                    properties:
                      backUp:
                        properties:
                          action: 
                            type: string
                          frequency: 
                            type: integer
                        type: object
                      env:
                        items:
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                    type: object

                type: object
            type: object
          status:
            description: ZookeeperClusterStatus defines the observed state of ZookeeperCluster
            properties:
              phase:
                type: string
              conditions:
                properties:
                  type: 
                    type: string
                  status:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
                  lastUpdateTime:
                    type: string
                  lastTransitionTime:
                    type: string
                type: object
            type: object
        type: object
